// AUTO-GENERATED by scripts/generate-art.mjs — do not edit by hand.
export const TILESET_COLS = 16;

export const T = {
  GRASS_A: 0,
  GRASS_B: 1,
  GRASS_FLOWER_R: 2,
  GRASS_FLOWER_Y: 3,
  GRASS_TUFT: 4,
  PATH: 5,
  SOIL: 6,
  FLOOR_A: 7,
  FLOOR_B: 8,
  WALL: 9,
  WALL_BASE: 10,
  VOID: 11,
  DOORMAT: 12,
  ROCK_A: 13,
  ROCK_B: 14,
  CLIFF: 15,
  SNOW: 16,
  WATER_A: 17,
  WATER_B: 18,
} as const;

export interface PropRegion {
  x: number;
  y: number;
  w: number;
  h: number;
}

export const PROPS = {
  tree: { x: 0, y: 0, w: 32, h: 32 },
  pine: { x: 32, y: 0, w: 32, h: 32 },
  house: { x: 64, y: 0, w: 96, h: 80 },
  fence_h: { x: 160, y: 0, w: 16, h: 16 },
  fence_v: { x: 176, y: 0, w: 16, h: 16 },
  sign: { x: 192, y: 0, w: 16, h: 16 },
  mailbox: { x: 208, y: 0, w: 16, h: 16 },
  bush: { x: 224, y: 0, w: 16, h: 16 },
  rock: { x: 240, y: 0, w: 16, h: 16 },
  crop_wheat: { x: 256, y: 0, w: 16, h: 16 },
  crop_carrot: { x: 272, y: 0, w: 16, h: 16 },
  crop_cabbage: { x: 288, y: 0, w: 16, h: 16 },
  crop_berry: { x: 304, y: 0, w: 16, h: 16 },
  crop_corn: { x: 320, y: 0, w: 16, h: 16 },
  tree_oak_s: { x: 336, y: 0, w: 16, h: 24 },
  tree_pine_s: { x: 352, y: 0, w: 16, h: 24 },
  tree_fruit_s: { x: 368, y: 0, w: 16, h: 24 },
  tree_oak_m: { x: 384, y: 0, w: 24, h: 28 },
  tree_pine_m: { x: 408, y: 0, w: 24, h: 28 },
  tree_fruit_m: { x: 432, y: 0, w: 24, h: 28 },
  tree_oak_l: { x: 456, y: 0, w: 32, h: 32 },
  tree_pine_l: { x: 0, y: 80, w: 32, h: 32 },
  tree_fruit_l: { x: 32, y: 80, w: 32, h: 32 },
  cairn: { x: 64, y: 80, w: 16, h: 16 },
  cabin: { x: 80, y: 80, w: 48, h: 40 },
  tower: { x: 128, y: 80, w: 32, h: 48 },
  flag: { x: 160, y: 80, w: 16, h: 28 },
  tent: { x: 176, y: 80, w: 32, h: 28 },
  campfire_a: { x: 208, y: 80, w: 16, h: 16 },
  campfire_b: { x: 224, y: 80, w: 16, h: 16 },
  log: { x: 240, y: 80, w: 16, h: 16 },
  bed_1: { x: 256, y: 80, w: 32, h: 24 },
  bed_2: { x: 288, y: 80, w: 32, h: 24 },
  bed_3: { x: 320, y: 80, w: 32, h: 24 },
  pot_a: { x: 352, y: 80, w: 16, h: 20 },
  pot_b: { x: 368, y: 80, w: 16, h: 20 },
  pot_c: { x: 384, y: 80, w: 16, h: 20 },
  toolrack: { x: 400, y: 80, w: 32, h: 32 },
  piano: { x: 432, y: 80, w: 32, h: 32 },
  desk: { x: 464, y: 80, w: 32, h: 24 },
  bed: { x: 0, y: 128, w: 32, h: 32 },
  bookshelf: { x: 32, y: 128, w: 16, h: 32 },
  table: { x: 48, y: 128, w: 32, h: 24 },
  chair: { x: 80, y: 128, w: 16, h: 16 },
  plant: { x: 96, y: 128, w: 16, h: 24 },
  fridge: { x: 112, y: 128, w: 16, h: 24 },
  counter: { x: 128, y: 128, w: 16, h: 16 },
  rug: { x: 144, y: 128, w: 48, h: 32 },
} as const satisfies Record<string, PropRegion>;

export type PropName = keyof typeof PROPS;
