// AUTO-GENERATED by scripts/generate-art.mjs — do not edit by hand.
export const TILESET_COLS = 16;

export const T = {
  GRASS_A: 0,
  GRASS_B: 1,
  GRASS_FLOWER_R: 2,
  GRASS_FLOWER_Y: 3,
  GRASS_TUFT: 4,
  PATH: 5,
  SOIL: 6,
  FLOOR_A: 7,
  FLOOR_B: 8,
  WALL: 9,
  WALL_BASE: 10,
  VOID: 11,
  DOORMAT: 12,
} as const;

export interface PropRegion {
  x: number;
  y: number;
  w: number;
  h: number;
}

export const PROPS = {
  tree: { x: 0, y: 0, w: 32, h: 32 },
  pine: { x: 32, y: 0, w: 32, h: 32 },
  house: { x: 64, y: 0, w: 96, h: 80 },
  fence_h: { x: 160, y: 0, w: 16, h: 16 },
  fence_v: { x: 176, y: 0, w: 16, h: 16 },
  sign: { x: 192, y: 0, w: 16, h: 16 },
  mailbox: { x: 208, y: 0, w: 16, h: 16 },
  bush: { x: 224, y: 0, w: 16, h: 16 },
  rock: { x: 240, y: 0, w: 16, h: 16 },
  crop_wheat: { x: 256, y: 0, w: 16, h: 16 },
  crop_carrot: { x: 272, y: 0, w: 16, h: 16 },
  crop_cabbage: { x: 288, y: 0, w: 16, h: 16 },
  crop_berry: { x: 304, y: 0, w: 16, h: 16 },
  crop_corn: { x: 320, y: 0, w: 16, h: 16 },
  piano: { x: 336, y: 0, w: 32, h: 32 },
  desk: { x: 368, y: 0, w: 32, h: 24 },
  bed: { x: 400, y: 0, w: 32, h: 32 },
  bookshelf: { x: 432, y: 0, w: 16, h: 32 },
  table: { x: 448, y: 0, w: 32, h: 24 },
  chair: { x: 480, y: 0, w: 16, h: 16 },
  plant: { x: 496, y: 0, w: 16, h: 24 },
  fridge: { x: 0, y: 80, w: 16, h: 24 },
  counter: { x: 16, y: 80, w: 16, h: 16 },
  rug: { x: 32, y: 80, w: 48, h: 32 },
} as const satisfies Record<string, PropRegion>;

export type PropName = keyof typeof PROPS;
